export const pages = [
  {
    page: 1,
    type: 'quiz',
    name: 'Physically active',
    question: 'Physically active',
    answers: [
      'Not very active',
      'Moderate',
      'I often go for a walk or exercise 1 - 2 times per week',
      'Active - I exercise 3 - 4 times per week',
      'Very active - I exercise 5+ times per week',
    ],
    icon: 'icon-physical-activity',
    background: 'bg-1',
    p: '',
    help: 'Your level of physical activity is the single most important factor which determines the amount of food in your meal program. Please select the answer most closely corresponding to your lifestyle in order to achieve your target weight.',
  },
  {
    page: 2,
    type: 'quiz',
    name: 'What is your typical day?',
    question: 'What is your typical day?',
    answers: [
      'I spend my day at the office, but i go out regularly',
      'Mostly at home',
      'Manual labor',
      'I spend the better part of my day on foot',
    ],
    icon: 'icon-have-energy',
    background: 'bg-2',
    p: '',
    help: 'The ketogenic diet is proven to increase the number of mitochondria, also known as the energy factories of brain cells.',
  },
  {
    page: 3,
    type: 'quiz',
    name: 'Weight',
    question: 'Is it easy for you to lose weight in general?',
    answers: [
      'Quite easy, if i work on it conscientiously',
      'It is a little bit difficult',
      'Weight loss has always been hard for me',
      "I haven't tried it yet",
    ],
    icon: 'icon-easy-to-lose-weight',
    background: 'bg-3',
    p: '',
    help: 'Keto will completely change how your organism process food by switching your main fuel source from carbs to fats. This will only make the weight loss process faster for you.',
  },
  {
    page: 4,
    type: 'card',
    name: 'Target weight',
    question: '',
    answers: '',
    icon: '',
    background: 'card-target-weight',
    p: 'Keto diet definitely work without exercise. On average people following a keto diet for several months are able to get sustainable results without a yo-yo effect.',
    help: 'Keto diet definitely work without exercise. On average people following a keto diet for several months are able to get sustainable results without a yo-yo effect.',
  },
  {
    page: 5,
    type: 'quiz',
    name: 'Pick your weight loss goal?',
    question: 'Pick your weight loss goal?',
    answers: [
      'Lose less than 8 kg',
      'Lose between 9 - 20 kg',
      'Lose more than 22 kg',
      'Maintain current weight',
    ],
    icon: 'icon-since-desired-weight',
    background: 'bg-4',
    p: '',
    help: "You don't need to worry about your desired weight anymore. AFter filling this quiz you will get a projection about your potential results after the first month on Keto.",
  },
  {
    page: 6,
    type: 'quiz',
    name: 'Calories care',
    question: 'Do you care about calories?',
    answers: ['Yes, i do a lot', 'I have so', 'I don`t really care'],
    icon: 'icon-care-about-calories',
    background: 'bg-5',
    p: '',
    help: 'With Your Keto meal plan, you will be able to stick to a calorie deficit without the need to count the calories in each product. Just follow the quantities in your daily recipes, and the results will come.',
  },
  {
    page: 7,
    type: 'card',
    name: 'Target weight',
    question: '',
    answers: '',
    icon: '',
    background: 'card-junk-food',
    p: "Strict control of calorie balance is unnecessary on the ketogenic diet. Each one of your meals on our plan is pre-calculated and contains only the products that you've selected.",
    help: "Strict control of calorie balance is unnecessary on the ketogenic diet. Each one of your meals on our plan is pre-calculated and contains only the products that you've selected.",
  },
  {
    page: 8,
    type: 'choice',
    name: 'Avoid',
    question: 'Avoid',
    answers: [
      {
        name: 'meet',
        value: 'chicken',
        svg: 'icon-chicken',
        type: 'answer',
      },
      { name: 'meet', value: 'pork', svg: 'icon-pork', type: 'answer' },
      { name: 'meet', value: 'beef', svg: 'icon-beef', type: 'answer' },
      {
        name: 'meet',
        value: 'bacon',
        svg: 'icon-bacon',
        type: 'answer',
      },
      { name: 'meet', value: 'lamb', svg: 'icon-cod', type: 'answer' },
      {
        name: 'meet',
        value: 'salmon',
        svg: 'icon-salmon',
        type: 'answer',
      },
      { name: 'meet', value: 'tuna', svg: 'icon-tuna', type: 'answer' },
      {
        name: 'meet',
        value: 'no-meat',
        svg: 'icon-no-meat',
        type: 'none',
      },
    ],
    icon: 'icon-meat',
    background: 'bg-6',
    p: 'Please select which proteins to avoid:',
    help: '',
  },
  {
    page: 9,
    type: 'choice',
    name: 'Veggies',
    question: 'Veggies',
    answers: [
      {
        name: 'veggies',
        value: 'broccoli',
        svg: 'icon-broccoli',
        type: 'answer',
      },
      {
        name: 'veggies',
        value: 'mushrooms',
        svg: 'icon-mushrooms',
        type: 'answer',
      },
      {
        name: 'veggies',
        value: 'zucchini',
        svg: 'icon-zucchini',
        type: 'answer',
      },
      {
        name: 'veggies',
        value: 'cauliflower',
        svg: 'icon-cauliflower',
        type: 'answer',
      },
      {
        name: 'veggies',
        value: 'aspargus',
        svg: 'icon-aspargus',
        type: 'answer',
      },
      {
        name: 'veggies',
        value: 'avocado',
        svg: 'icon-avocado',
        type: 'answer',
      },
    ],
    icon: 'icon-veggies',
    background: 'bg-7',
    p: 'Please select which veggies you would like to be included:',
    help: 'The vegetables you have designated as "INCLUDE" may also be included, so that your diet is well-balanced. To completely exclude a product, click on the "EXCLUDE" column.',
  },
  {
    page: 10,
    type: 'choice',
    name: 'Products',
    question: 'Products',
    answers: [
      {
        name: 'products',
        value: 'eggs',
        svg: 'icon-eggs',
        type: 'answer',
      },
      {
        name: 'products',
        value: 'nuts',
        svg: 'icon-nuts',
        type: 'answer',
      },
      {
        name: 'products',
        value: 'cheese',
        svg: 'icon-cheese',
        type: 'answer',
      },
      {
        name: 'products',
        value: 'cottage-cheese',
        svg: 'icon-cottagecheese',
        type: 'answer',
      },
      {
        name: 'products',
        value: 'butter',
        svg: 'icon-butter',
        type: 'answer',
      },
      {
        name: 'products',
        value: 'coconut',
        svg: 'icon-coconut',
        type: 'answer',
      },
      {
        name: 'products',
        value: 'tofu',
        svg: 'icon-tofu',
        type: 'answer',
      },
    ],
    icon: 'icon-products',
    background: 'bg-8',
    p: 'Other foods to avoid:',
    help: 'We recommend you to exclude only the food that you are allergic to, should not eat due to a medical condition or a dietary restriction, or foods that you absolutely hate. The more products you include, the more diverse and effective your diet will be.',
  },
  {
    page: 11,
    type: 'quiz',
    name: 'Everyday',
    question: 'Describe a typical day for you',
    answers: [
      'AT THE OFFICE',
      'AT THE OFFICE, BUT I GO OUT ON A REGULAR BASIS',
      'I SPEND THE BETTER PART OF THE DAY ON FOOT',
      'MANUAL LABOR',
      'I MOSTLY STAY AT HOME',
    ],
    icon: 'icon-sunday',
    background: 'bg-9',
    p: '',
    help: 'Your lifestyle has a significant impact on the amount of food included in your personalized meal program. If you can not find the exact answer choose the one that most closely corresponds to your daily life.',
  },
  {
    page: 12,
    type: 'quiz',
    name: 'Sleep',
    question: 'How many hours of sleep do you usually get per night?',
    answers: [
      'Less than 5 hours per night',
      '5-6 hours per night',
      '7-8 hours',
      '8 hours and more',
    ],
    icon: 'icon-sleep-per-night',
    background: 'bg-10',
    p: '',
    help: 'Getting enough sleep will boost your Keto Transformation.',
  },
  {
    page: 13,
    type: 'quiz',
    name: 'Stress',
    question: 'How often do you feel stressed out?',
    answers: ['Almost never', 'Sometimes', 'Very often', 'Almost always'],
    icon: 'icon-stressed-out',
    background: 'bg-11',
    p: '',
    help: 'Following a ketogenic meal plan is proven to be beneficial for treating mood disorders, including stress and depression. Using fats instead of carbs as a main fuel source for the body exerts positive effects on the brain and nervous system overall.',
  },
  {
    page: 14,
    type: 'quiz',
    name: 'Blood sugar',
    question: 'Is your blood sugar level in normal range?',
    answers: ['I don`t know', 'Yes, everything is okay', 'I suffer from diabetes'],
    icon: 'icon-blood-sugar',
    background: 'bg-12',
    p: '',
    help: 'Blood glucose is a primary marker for determining the risk of diabetes and heart disease. Keto has the potential to seriously decrease the levels of sugar in our blood.',
  },
  {
    page: 15,
    type: 'card',
    name: 'Blood sugar diagram',
    question: '',
    answers: '',
    icon: '',
    background: 'card-blood-sugar',
    p: 'Several studies indicate that restricting carb intake to 20–50 grams per day can significantly reduce blood sugar levels, promote weight loss, and improve cardiovascular health for people with diabetes. Medical specialists often recommend ketogenic diet to people with diabetes 2 because carbohydrates turn into sugar and can cause blood sugar spikes.',
    help: 'Reducing the daily carb intake to 5% or under can drastically reduce your blood sugar levels. Medical specialists often recommend ketogenic diet to people with diabetes 2 because carbohydrates turn into sugar and can cause blood sugar spikes.',
  },
  {
    page: 16,
    type: 'choice-line',
    name: 'Bad habits',
    question: 'Which of the following is true for you',
    answers: [
      {
        name: 'bad-habits',
        value: 'I have bad sleeping schedule',
        type: 'answer',
      },
      {
        name: 'bad-habits',
        value: "I don't get enough sleep",
        type: 'answer',
      },
      {
        name: 'bad-habits',
        value: 'I eat late at night',
        type: 'answer',
      },
      {
        name: 'bad-habits',
        value: 'I eat too much salt',
        type: 'answer',
      },
      {
        name: 'bad-habits',
        value: "I can't stop eating sugar",
        type: 'answer',
      },
      { name: 'bad-habits', value: 'None of the above', type: 'none' },
    ],
    icon: 'icon-true',
    background: 'bg-13',
    p: 'You can choose multiple options:',
    help: "To be sure you'll achieve your goal, it is necessary to take your harmful habits into consideration. This should help you follow your diet.",
  },
  {
    page: 17,
    type: 'quiz',
    name: 'Hungry',
    question: 'What time of day are you most hungry?',
    answers: ['Morning', 'Afternoon', 'Evening', 'Night', 'I feel hungry all the time'],
    icon: 'icon-hungry-most',
    background: 'bg-14',
    p: '',
    help: 'Combining Keto with intermittent fasting may further help you reach your weight loss goals.',
  },
  {
    page: 18,
    type: 'card',
    name: 'Appetite diagram',
    question: '',
    answers: '',
    icon: '',
    background: 'card-appetite',
    p: 'The keto diet may help promote weight loss in several ways, including boosting metabolism and reducing appetite.  After you get into ketosis you will suddenly forget about your carb cravings, while the variety of foods and precalculated portions will keep you full during the day.',
    help: 'Keto diet is a proven method for appetite reduction. After you get into ketosis you will suddenly forget about your carb cravings, while the variety of foods and precalculated portions will keep you full during the day.',
  },
  {
    page: 19,
    type: 'quiz',
    name: 'Eating',
    question: 'Do you tend to get into emotional eating?',
    answers: ['Yes, very often', 'Sometimes', 'Rarely', 'No, never'],
    icon: 'icon-emotional-eating',
    background: 'bg-15',
    p: '',
    help: 'The Keto diet is proven to reduce cravings. Following your meal plan will make you eat the right food at the right time, so you feel energetic and well-fed during the day.',
  },
  {
    page: 20,
    type: 'quiz',
    name: 'Junk food',
    question: 'How often do you eat out?',
    answers: [
      'Almost everyday',
      'Once or twice a week',
      'Few times a month',
      'Once every few months',
      'Almost never',
    ],
    icon: 'icon-eat-junk-food',
    background: 'bg-16',
    p: '',
    help: "It's great that with Keto you can still enjoy a variety of tasty meals and snacks.",
  },
  {
    page: 21,
    type: 'quiz',
    name: 'Eat out',
    question: 'Time to cook?',
    answers: [
      'Minimal - Up to 15 min per meal',
      'Average - Up to 40 min per meal',
      'Plenty - 40+ min per meal',
    ],
    icon: 'icon-eat-out-week',
    background: 'bg-17',
    p: '',
    help: "Low carb diets like Keto work anywhere. Even if you don't have enough time for cooking today you can always substitute your meal with a Keto dish in the local restaurant.",
  },
  {
    page: 22,
    type: 'card',
    name: 'Restaurants diagram',
    question: '',
    answers: '',
    icon: '',
    background: 'card-restaurants',
    p: "Starting a keto diet doesn't mean you have to eat every meal at home. There are plenty of options you can find at the local restaurant, or even the supermarket.",
    help: "Keto diet doesn't require that you prepare all your meals by yourself. There are plenty of options you can find at the local restaurant, or even the supermarket.",
  },
  {
    page: 23,
    type: 'quiz',
    name: 'Skills',
    question: 'How often do you consume alcohol?',
    answers: [
      'Sometimes - Few times a month',
      'Very often - Two or three times a week',
      'Almost everyday',
      'Almost never',
      'I don`t consume alcohol',
    ],
    icon: 'icon-cooking-skills',
    background: 'bg-18',
    p: '',
    help: 'Even if you start Keto with beginner cooking skills, following your personalized meal plan will help you start enjoying the process of preparing your food.',
  },
  {
    page: 24,
    type: 'choice-line',
    name: 'Drink',
    question: 'What do you like to drink during the day?',
    answers: [
      { name: 'drink', value: 'Tea', type: 'answer' },
      { name: 'drink', value: 'Coffee', type: 'answer' },
      { name: 'drink', value: 'Water', type: 'answer' },
      { name: 'drink', value: 'Sparkling water', type: 'answer' },
      { name: 'drink', value: 'Soda', type: 'answer' },
      { name: 'drink', value: 'Juice', type: 'answer' },
      { name: 'drink', value: 'None of the above', type: 'none' },
    ],
    icon: 'icon-drink-during-day',
    background: 'bg-19',
    p: 'You can choose multiple options:',
    help: 'Some drinks may increase your carb intake, so it is better to follow the instructions of your meal plan, where you will find what is best to drink during Keto.',
  },
  {
    page: 25,
    type: 'quiz',
    name: 'Water',
    question: 'How much water do you drink per day?',
    answers: [
      'Less than 2 glasses (500 ml)',
      '2-4 glasses (500 - 1000 ml)',
      '4-6 glasses (1000 - 1500 ml)',
      '6-8 glasses (1500 - 2000 ml)',
      'More than 8 glasses (2000+ ml)',
    ],
    icon: 'icon-water-per-day',
    background: 'bg-20',
    p: '',
    help: 'The Keto diet has a diuretic effect which increases the hydration needs of the organism. Drinking enough water will help you make the process of changing your body fuel quicker.',
  },
  {
    page: 26,
    type: 'card',
    name: 'Water diagram',
    question: '',
    answers: '',
    icon: '',
    background: 'card-water',
    p: 'You can get even better results combining Keto with higher water intake. At the end of the quiz we will recommend you a personal daily water intake during your Keto transformation.',
    help: 'Most people got even better results combining Keto with higher water intake. At the end of the quiz we will recommend you a personal daily water intake during your Keto transformation.',
  },
  {
    page: 27,
    type: 'quiz',
    name: 'Alcohol',
    question: 'Health conditions?',
    answers: ['Type 1 diabetes', 'Type 2 diabetes', 'High blood pressure', 'None of the above'],
    icon: 'icon-consume-alcohol',
    background: 'bg-21',
    p: '',
    help: 'There are some alcohols which are low-carb and Keto-friendly like wine, vodka, whiskey, gin, tequila, rum and others. Of course, you can consume them in limited quantity as they are high in calories which can impact the weight loss process.',
  },
  {
    page: 28,
    type: 'choice-line',
    name: 'Motivation',
    question: 'What motivates you the most in your life?',
    answers: [
      { name: 'motivation', value: 'My family', type: 'answer' },
      { name: 'motivation', value: 'My friends', type: 'answer' },
      { name: 'motivation', value: 'My coworkers', type: 'answer' },
      {
        name: 'motivation',
        value: 'Successful people',
        type: 'answer',
      },
      { name: 'motivation', value: 'God', type: 'answer' },
      {
        name: 'motivation',
        value: 'I am self-motivated',
        type: 'answer',
      },
      { name: 'motivation', value: 'None of the above', type: 'none' },
    ],
    icon: 'icon-motivates-you-most',
    background: 'bg-22',
    p: 'You can choose multiple options:',
    help: 'The main factor behind your healthy weight-loss transformation is your motivation. Every journey starts with the right mindset, so find what drives you forward, and we will help with the rest.',
  },
  {
    page: 29,
    type: 'quiz',
    name: 'Journey',
    question: 'When do you want to start your keto journey?',
    answers: ['Right now', 'Tomorrow', 'Next week', 'Next month', 'I don`t know'],
    icon: 'icon-start-keto-journey',
    background: 'bg-23',
    p: '',
    help: 'The earlier you start, the sooner you will reach your goals.',
  },
  {
    page: 30,
    type: 'card',
    name: 'Water diagram',
    question: '',
    answers: '',
    icon: '',
    background: 'card-your-way',
    p: "Actually, Your Keto journey has already started with a small step towards your target. Filling this quiz made you think about your lifestyle, and brain activity is one of the things that make our body uses a lot of energy. Now let's keep up with the progress and use that first step as a building block to your success. Continue to the next step to learn about important metrics, such as BMI, Metabolic age, Daily water intake and more useful info.",
    help: "Now let's keep up with the progress and use that first step as a building block to your success. Continue to the next step to learn about important metrics, such as BMI, Metabolic age, Daily water intake and more useful info.",
  },
  {
    page: 31,
    type: 'choice-line',
    name: 'Body parts',
    question: 'Which body area do you need to focus on?',
    answers: [
      {
        name: 'body-parts',
        value: 'Arms and shoulders',
        type: 'answer',
      },
      { name: 'body-parts', value: 'Hips and thighs', type: 'answer' },
      { name: 'body-parts', value: 'Belly', type: 'answer' },
      { name: 'body-parts', value: 'Back', type: 'answer' },
      { name: 'body-parts', value: 'Chest', type: 'answer' },
      { name: 'body-parts', value: 'None of the above', type: 'none' },
    ],
    icon: 'icon-body-parts',
    background: 'bg-24',
    p: 'You can choose multiple options:',
    help: 'Ketogenic diet tend to reduce total weight and body fat percentage much more effective than low-fat diets.',
  },
  {
    page: 32,
    type: 'measurements',
    name: 'Measurements',
    question: '',
    answers: '',
    icon: '',
    background: '',
    p: '',
    help: 'This meal program is individual and takes your body measurements into consideration.',
  },
];

export const qtyPages = pages.length;
