export const pages = [
  {
    page: 1,
    type: 'quiz',
    name: 'Physical activity',
    question: 'Physical activity',
    answers: [
      'ALMOST NO PHYSICAL ACTIVITY',
      'I OFTEN GO FOR A WALK',
      'I EXERCISE 1 - 2 TIMES A WEEK',
      'I EXERCISE 3 - 5 TIMES A WEEK',
      'I EXERCISE 5 - 7 TIMES A WEEK',
    ],
    icon: 'icon-physical-activity',
    background: 'bg-1',
    p: '',
  },
  {
    page: 2,
    type: 'quiz',
    name: 'Energy',
    question: 'Do you have the energy and focus you need to meet your daily challenges?',
    answers: [
      'YES! TOTALLY ENERGETIC',
      'MY ENERGY LEVELS FALL DURING THE DAY',
      'I USUALLY FEEL WEAK AND LAZY',
      'I FEEL DISTRACTED EVEN AFTER BEING ENERGETIC',
    ],
    icon: 'icon-have-energy',
    background: 'bg-2',
    p: '',
  },
  {
    page: 3,
    type: 'quiz',
    name: 'Easy weight',
    question: 'Is it easy for you to lose weight?',
    answers: [
      'IF I WORK ON IT - QUITE EASY',
      'WEIGHT LOSS IS A LITTLE BIT DIFFICULT FOR ME',
      'IT HAS ALWAYS BEEN HARD',
    ],
    icon: 'icon-easy-to-lose-weight',
    background: 'bg-3',
    p: '',
  },
  {
    page: 4,
    type: 'card',
    name: 'Target weight',
    question: '',
    answers: '',
    icon: '',
    background: 'card-target-weight',
    p: 'Keto can be really effective even without excercising. On average people following a keto diet for several months are able to get sustainable results without a yo-yo effect.',
  },
  {
    page: 5,
    type: 'quiz',
    name: 'Desired weight',
    question: 'How long has it been since you were at your desired weight?',
    answers: ['I AM RIGHT NOW', 'LESS THAN A YEAR AGO', 'MORE THAN A YEAR AGO', 'I CAN’T REMEMBER'],
    icon: 'icon-since-desired-weight',
    background: 'bg-4',
    p: '',
  },
  {
    page: 6,
    type: 'quiz',
    name: 'Calories',
    question: 'Do you care about calories?',
    answers: [
      'YES, I COUNT CALORIES AND MACROS',
      'I HAVE SOME IDEA ABOUT THE CALORIES OF MY DAILY MEALS',
      'I DON’T CARE ABOUT CALORIES',
    ],
    icon: 'icon-care-about-calories',
    background: 'bg-5',
    p: '',
  },
  {
    page: 7,
    type: 'card',
    name: 'Target weight',
    question: '',
    answers: '',
    icon: '',
    background: 'card-junk-food',
    p: "With YourKeto diet you can forget about calorie counting. Each one of your meals is pre-calculated and contains only the products that you've selected during the quiz.",
  },
  {
    page: 8,
    type: 'choice',
    name: 'Meat',
    question: 'Meat',
    answers: [
      { name: 'meet', value: 'chicken', svg: 'icon-chicken', type: 'answer' }, ///имя у всех чекбоксов должно быть одинаково
      { name: 'meet', value: 'pork', svg: 'icon-pork', type: 'answer' },
      { name: 'meet', value: 'beef', svg: 'icon-beef', type: 'answer' },
      { name: 'meet', value: 'bacon', svg: 'icon-bacon', type: 'answer' },
      { name: 'meet', value: 'cod', svg: 'icon-cod', type: 'answer' },
      { name: 'meet', value: 'salmon', svg: 'icon-salmon', type: 'answer' },
      { name: 'meet', value: 'tuna', svg: 'icon-tuna', type: 'answer' },
      { name: 'meet', value: 'no-meat', svg: 'icon-no-meat', type: 'none' }, ///отрицательный тип ответа должен стоять всегда вконце
    ],
    icon: 'icon-meat',
    background: 'bg-6',
    p: 'Please select which meat you would like to be included:',
  },
  {
    page: 9,
    type: 'choice',
    name: 'Veggies',
    question: 'Veggies',
    answers: [
      { name: 'veggies', value: 'broccoli', svg: 'icon-broccoli', type: 'answer' }, ///имя у всех чекбоксов должно быть одинаково
      { name: 'veggies', value: 'mushrooms', svg: 'icon-mushrooms', type: 'answer' },
      { name: 'veggies', value: 'zucchini', svg: 'icon-zucchini', type: 'answer' },
      { name: 'veggies', value: 'cauliflower', svg: 'icon-cauliflower', type: 'answer' },
      { name: 'veggies', value: 'aspargus', svg: 'icon-aspargus', type: 'answer' },
      { name: 'veggies', value: 'avocado', svg: 'icon-avocado', type: 'answer' }, ///отрицательный тип ответа должен стоять всегда вконце и type: 'none'
    ],
    icon: 'icon-veggies',
    background: 'bg-7',
    p: 'Please select which veggies you would like to be included:',
  },
  {
    page: 10,
    type: 'choice',
    name: 'Products',
    question: 'Products',
    answers: [
      { name: 'products', value: 'eggs', svg: 'icon-eggs', type: 'answer' }, ///имя у всех чекбоксов должно быть одинаково
      { name: 'products', value: 'nuts', svg: 'icon-nuts', type: 'answer' },
      { name: 'products', value: 'cheese', svg: 'icon-cheese', type: 'answer' },
      { name: 'products', value: 'cottage-cheese', svg: 'icon-cottagecheese', type: 'answer' },
      { name: 'products', value: 'butter', svg: 'icon-butter', type: 'answer' },
      { name: 'products', value: 'coconut', svg: 'icon-coconut', type: 'answer' },
      { name: 'products', value: 'tofu', svg: 'icon-tofu', type: 'answer' }, ///отрицательный тип ответа должен стоять всегда вконце и type: 'none'
    ],
    icon: 'icon-products',
    background: 'bg-8',
    p: 'Please select which products you would like to be included:',
  },
  {
    page: 11,
    type: 'quiz',
    name: 'Everyday',
    question: 'Describe a typical day for you',
    answers: [
      'AT THE OFFICE',
      'AT THE OFFICE, BUT I GO OUT ON A REGULAR BASIS',
      'I SPEND THE BETTER PART OF THE DAY ON FOOT',
      'MANUAL LABOR',
      'I MOSTLY STAY AT HOME',
    ],
    icon: 'icon-sunday',
    background: 'bg-9',
    p: '',
  },
  {
    page: 12,
    type: 'quiz',
    name: 'Sleep',
    question: 'How many hours of sleep do you get per night?',
    answers: ['LESS THAN 5 HOURS', '5-6 HOURS', '7-8 HOURS', 'MORE THAN 8 HOURS'],
    icon: 'icon-sleep-per-night',
    background: 'bg-10',
    p: '',
  },
  {
    page: 13,
    type: 'quiz',
    name: 'Stress',
    question: 'How often do you feel stressed out?',
    answers: ['NEVER', 'SOMETIMES', 'OFTEN', 'ALMOST ALWAYS'],
    icon: 'icon-stressed-out',
    background: 'bg-11',
    p: '',
  },
  {
    page: 14,
    type: 'quiz',
    name: 'Blood sugar',
    question: 'Is your blood sugar level in normal range?',
    answers: [
      'I AM NOT SURE',
      'YES, EVERYTHING IS UNDER CONTROL',
      'I HAVE INCREASED BLOOD SUGAR LEVEL OCCASIONALLY',
      'NO, I SUFFER FROM DIABETES',
    ],
    icon: 'icon-blood-sugar',
    background: 'bg-12',
    p: '',
  },
  {
    page: 15,
    type: 'card',
    name: 'Blood sugar diagram',
    question: '',
    answers: '',
    icon: '',
    background: 'card-blood-sugar',
    p: 'Reducing the daily carb intake to 5% or under can drastically reduce your blood sugar levels. Medical specialists often recommend ketogenic diet to people with diabetes 2 because carbohydrates turn into sugar and can cause blood sugar spikes.',
  },
  {
    page: 16,
    type: 'choice-line',
    name: 'Bad habits',
    question: 'Which of the following is true for you',
    answers: [
      { name: 'products', value: 'I DO NOT GET ENOUGH SLEEP', type: 'answer' }, ///имя у всех чекбоксов должно быть одинаково
      { name: 'products', value: 'I EAT LATE AT NIGHT', type: 'answer' },
      { name: 'products', value: 'I CONSUME A LOT OF SALT', type: 'answer' },
      { name: 'products', value: 'I CANNOT GIVE UP EATING SWEETS', type: 'answer' },
      { name: 'products', value: 'I LOVE SOFT DRINKS', type: 'answer' },
      { name: 'products', value: 'None of the above', type: 'none' }, ///отрицательный тип ответа должен стоять всегда вконце и type: 'none'
    ],
    icon: 'icon-true',
    background: 'bg-13',
    p: 'It is possible to select multiple answers:',
  },
];
