export const pages = [
  {
    page: 1,
    type: 'quiz',
    name: 'Physical activity',
    question: 'Physical activity',
    answers: [
      'ALMOST NO PHYSICAL ACTIVITY',
      'I OFTEN GO FOR A WALK',
      'I EXERCISE 1 - 2 TIMES A WEEK',
      'I EXERCISE 3 - 5 TIMES A WEEK',
      'I EXERCISE 5 - 7 TIMES A WEEK',
    ],
    icon: 'icon-physical-activity',
    background: 'bg-1',
    p: '',
    help: 'Your level of physical activity is the single most important factor which determines the amount of food in your meal program. Please select the answer most closely corresponding to your lifestyle in order to achieve your target weight.',
  },
  {
    page: 2,
    type: 'quiz',
    name: 'Energy',
    question: 'Do you have the energy and focus you need to meet your daily challenges?',
    answers: [
      'YES! TOTALLY ENERGETIC',
      'MY ENERGY LEVELS FALL DURING THE DAY',
      'I USUALLY FEEL WEAK AND LAZY',
      'I FEEL DISTRACTED EVEN AFTER BEING ENERGETIC',
    ],
    icon: 'icon-have-energy',
    background: 'bg-2',
    p: '',
    help: 'The ketogenic diet is proven to increase the number of mitochondria, also known as the energy factories of brain cells.',
  },
  {
    page: 3,
    type: 'quiz',
    name: 'Easy weight',
    question: 'Is it easy for you to lose weight?',
    answers: [
      'IF I WORK ON IT - QUITE EASY',
      'WEIGHT LOSS IS A LITTLE BIT DIFFICULT FOR ME',
      'IT HAS ALWAYS BEEN HARD',
    ],
    icon: 'icon-easy-to-lose-weight',
    background: 'bg-3',
    p: '',
    help: 'Keto will completely change how your organism process food by switching your main fuel source from carbs to fats. This will only make the weight loss process faster for you.',
  },
  {
    page: 4,
    type: 'card',
    name: 'Target weight',
    question: '',
    answers: '',
    icon: '',
    background: 'card-target-weight',
    p: 'Keto can be really effective even without excercising. On average people following a keto diet for several months are able to get sustainable results without a yo-yo effect.',
    help: 'Keto can be really effective even without excercising. On average people following a keto diet for several months are able to get sustainable results without a yo-yo effect.',
  },
  {
    page: 5,
    type: 'quiz',
    name: 'Desired weight',
    question: 'How long has it been since you were at your desired weight?',
    answers: ['I AM RIGHT NOW', 'LESS THAN A YEAR AGO', 'MORE THAN A YEAR AGO', 'I CAN’T REMEMBER'],
    icon: 'icon-since-desired-weight',
    background: 'bg-4',
    p: '',
    help: "You don't need to worry about your desired weight anymore. AFter filling this quiz you will get a projection about your potential results after the first month on Keto.",
  },
  {
    page: 6,
    type: 'quiz',
    name: 'Calories',
    question: 'Do you care about calories?',
    answers: [
      'YES, I COUNT CALORIES AND MACROS',
      'I HAVE SOME IDEA ABOUT THE CALORIES OF MY DAILY MEALS',
      'I DON’T CARE ABOUT CALORIES',
    ],
    icon: 'icon-care-about-calories',
    background: 'bg-5',
    p: '',
    help: "With Your Keto meal plan, you will be able to stick to a calorie deficit without the need to count the calories in each product. Just follow the quantities in your daily recipes, and the results will come.",
  },
  {
    page: 7,
    type: 'card',
    name: 'Target weight',
    question: '',
    answers: '',
    icon: '',
    background: 'card-junk-food',
    p: "With YourKeto diet you can forget about calorie counting. Each one of your meals is pre-calculated and contains only the products that you've selected during the quiz.",
    help: "With YourKeto diet you can forget about calorie counting. Each one of your meals is pre-calculated and contains only the products that you've selected during the quiz.",
  },
  {
    page: 8,
    type: 'choice',
    name: 'Meat',
    question: 'Meat',
    answers: [
      { name: 'meet', value: 'chicken', svg: 'icon-chicken', type: 'answer' }, ///имя у всех чекбоксов должно быть одинаково
      { name: 'meet', value: 'pork', svg: 'icon-pork', type: 'answer' },
      { name: 'meet', value: 'beef', svg: 'icon-beef', type: 'answer' },
      { name: 'meet', value: 'bacon', svg: 'icon-bacon', type: 'answer' },
      { name: 'meet', value: 'cod', svg: 'icon-cod', type: 'answer' },
      { name: 'meet', value: 'salmon', svg: 'icon-salmon', type: 'answer' },
      { name: 'meet', value: 'tuna', svg: 'icon-tuna', type: 'answer' },
      { name: 'meet', value: 'no-meat', svg: 'icon-no-meat', type: 'none' }, ///отрицательный тип ответа должен стоять всегда вконце
    ],
    icon: 'icon-meat',
    background: 'bg-6',
    p: 'Please select which meat you would like to be included:',
    help: "The products that you choose to be Excluded will not be found in your personalized meal plan. We recommend you to exclude only the food that you are allergic to, should not eat due to a medical condition or a dietary restriction, or foods that you absolutely hate. The more products you include, the more diverse and effective your diet will be.",
  },
  {
    page: 9,
    type: 'choice',
    name: 'Veggies',
    question: 'Veggies',
    answers: [
      { name: 'veggies', value: 'broccoli', svg: 'icon-broccoli', type: 'answer' }, ///имя у всех чекбоксов должно быть одинаково
      { name: 'veggies', value: 'mushrooms', svg: 'icon-mushrooms', type: 'answer' },
      { name: 'veggies', value: 'zucchini', svg: 'icon-zucchini', type: 'answer' },
      { name: 'veggies', value: 'cauliflower', svg: 'icon-cauliflower', type: 'answer' },
      { name: 'veggies', value: 'aspargus', svg: 'icon-aspargus', type: 'answer' },
      { name: 'veggies', value: 'avocado', svg: 'icon-avocado', type: 'answer' }, ///отрицательный тип ответа должен стоять всегда вконце и type: 'none'
    ],
    icon: 'icon-veggies',
    background: 'bg-7',
    p: 'Please select which veggies you would like to be included:',
    help: 'The vegetables you have designated as "INCLUDE" may also be included, so that your diet is well-balanced. To completely exclude a product, click on the "EXCLUDE" column.',
  },
  {
    page: 10,
    type: 'choice',
    name: 'Products',
    question: 'Products',
    answers: [
      { name: 'products', value: 'eggs', svg: 'icon-eggs', type: 'answer' }, ///имя у всех чекбоксов должно быть одинаково
      { name: 'products', value: 'nuts', svg: 'icon-nuts', type: 'answer' },
      { name: 'products', value: 'cheese', svg: 'icon-cheese', type: 'answer' },
      { name: 'products', value: 'cottage-cheese', svg: 'icon-cottagecheese', type: 'answer' },
      { name: 'products', value: 'butter', svg: 'icon-butter', type: 'answer' },
      { name: 'products', value: 'coconut', svg: 'icon-coconut', type: 'answer' },
      { name: 'products', value: 'tofu', svg: 'icon-tofu', type: 'answer' }, ///отрицательный тип ответа должен стоять всегда вконце и type: 'none'
    ],
    icon: 'icon-products',
    background: 'bg-8',
    p: 'Please select which products you would like to be included:',
    help: "We recommend you to exclude only the food that you are allergic to, should not eat due to a medical condition or a dietary restriction, or foods that you absolutely hate. The more products you include, the more diverse and effective your diet will be.",
  },
  {
    page: 11,
    type: 'quiz',
    name: 'Everyday',
    question: 'Describe a typical day for you',
    answers: [
      'AT THE OFFICE',
      'AT THE OFFICE, BUT I GO OUT ON A REGULAR BASIS',
      'I SPEND THE BETTER PART OF THE DAY ON FOOT',
      'MANUAL LABOR',
      'I MOSTLY STAY AT HOME',
    ],
    icon: 'icon-sunday',
    background: 'bg-9',
    p: '',
    help: "Your lifestyle has a significant impact on the amount of food included in your personalized meal program. If you can not find the exact answer choose the one that most closely corresponds to your daily life.",
  },
  {
    page: 12,
    type: 'quiz',
    name: 'Sleep',
    question: 'How many hours of sleep do you get per night?',
    answers: ['LESS THAN 5 HOURS', '5-6 HOURS', '7-8 HOURS', 'MORE THAN 8 HOURS'],
    icon: 'icon-sleep-per-night',
    background: 'bg-10',
    p: '',
    help: "Getting enough sleep will boost your Keto Transformation.",
  },
  {
    page: 13,
    type: 'quiz',
    name: 'Stress',
    question: 'How often do you feel stressed out?',
    answers: ['NEVER', 'SOMETIMES', 'OFTEN', 'ALMOST ALWAYS'],
    icon: 'icon-stressed-out',
    background: 'bg-11',
    p: '',
    help: "Following a ketogenic meal plan is proven to be beneficial for treating mood disorders, including stress and depression. Using fats instead of carbs as a main fuel source for the body exerts positive effects on the brain and nervous system overall.",

  },
  {
    page: 14,
    type: 'quiz',
    name: 'Blood sugar',
    question: 'Is your blood sugar level in normal range?',
    answers: [
      'I AM NOT SURE',
      'YES, EVERYTHING IS UNDER CONTROL',
      'I HAVE INCREASED BLOOD SUGAR LEVEL OCCASIONALLY',
      'NO, I SUFFER FROM DIABETES',
    ],
    icon: 'icon-blood-sugar',
    background: 'bg-12',
    p: '',
    help: "Blood glucose is a primary marker for determining the risk of diabetes and heart disease. Keto has the potential to seriously decrease the levels of sugar in our blood.",
  },
  {
    page: 15,
    type: 'card',
    name: 'Blood sugar diagram',
    question: '',
    answers: '',
    icon: '',
    background: 'card-blood-sugar',
    p: 'Reducing the daily carb intake to 5% or under can drastically reduce your blood sugar levels. Medical specialists often recommend ketogenic diet to people with diabetes 2 because carbohydrates turn into sugar and can cause blood sugar spikes.',
    help: "Reducing the daily carb intake to 5% or under can drastically reduce your blood sugar levels. Medical specialists often recommend ketogenic diet to people with diabetes 2 because carbohydrates turn into sugar and can cause blood sugar spikes.",
  },
  {
    page: 16,
    type: 'choice-line',
    name: 'Bad habits',
    question: 'Which of the following is true for you',
    answers: [
      { name: 'bad-habits', value: 'I DO NOT GET ENOUGH SLEEP', type: 'answer' }, ///имя у всех чекбоксов должно быть одинаково
      { name: 'bad-habits', value: 'I EAT LATE AT NIGHT', type: 'answer' },
      { name: 'bad-habits', value: 'I CONSUME A LOT OF SALT', type: 'answer' },
      { name: 'bad-habits', value: 'I CANNOT GIVE UP EATING SWEETS', type: 'answer' },
      { name: 'bad-habits', value: 'I LOVE SOFT DRINKS', type: 'answer' },
      { name: 'bad-habits', value: 'None of the above', type: 'none' }, ///отрицательный тип ответа должен стоять всегда вконце и type: 'none'
    ],
    icon: 'icon-true',
    background: 'bg-13',
    p: 'It is possible to select multiple answers:',
    help: "To be sure you'll achieve your goal, it is necessary to take your harmful habits into consideration. This should help you follow your diet.",
  },
  {
    page: 17,
    type: 'quiz',
    name: 'Hungry',
    question: 'At what time during the day do you feel hungry the most?',
    answers: ['MORNING', 'NOON', 'AFTERNOON', 'EVENING', 'I FEEL HUNGRY ALL THE TIME'],
    icon: 'icon-hungry-most',
    background: 'bg-14',
    p: '',
    help: "Combining Keto with intermittent fasting may further help you reach your weight loss goals.",
  },
  {
    page: 18,
    type: 'card',
    name: 'Appetite diagram',
    question: '',
    answers: '',
    icon: '',
    background: 'card-appetite',
    p: 'Keto diet is a proven method for appetite reduction. After you get into ketosis you will suddenly forget about your carb cravings, while the variety of foods and precalculated portions will keep you full during the day.',
    help: "Keto diet is a proven method for appetite reduction. After you get into ketosis you will suddenly forget about your carb cravings, while the variety of foods and precalculated portions will keep you full during the day.",
  },
  {
    page: 19,
    type: 'quiz',
    name: 'Eating',
    question: 'Do you tend to get into emotional eating?',
    answers: ['YES', 'SOMETIMES', 'RARELY', 'NEVER'],
    icon: 'icon-emotional-eating',
    background: 'bg-15',
    p: '',
    help: "The Keto diet is proven to reduce cravings. Following your meal plan will make you eat the right food at the right time, so you feel energetic and well-fed during the day.",
  },
  {
    page: 20,
    type: 'quiz',
    name: 'Junk food',
    question: 'How often do you eat junk/fast food?',
    answers: [
      'NEVER OR RARELY',
      '1-2 TIMES PER WEEK',
      '3-4 TIMES PER WEEK',
      '5-6 TIMES PER WEEK',
      'EVERYDAY',
    ],
    icon: 'icon-eat-junk-food',
    background: 'bg-16',
    p: '',
    help: "It's great that with Keto you can still enjoy a variety of tasty meals and snacks.",
  },
  {
    page: 21,
    type: 'quiz',
    name: 'Eat out',
    question: 'How many times do you eat out during the week?',
    answers: ['ON A DAILY BASIS', 'ONCE A WEEK', 'FEW TIMES A MONTH', 'RARELY', 'NEVER'],
    icon: 'icon-eat-out-week',
    background: 'bg-17',
    p: '',
    help: "Low carb diets like Keto work anywhere. Even if you don't have enough time for cooking today you can always substitute your meal with a Keto dish in the local restaurant.",
  },
  {
    page: 22,
    type: 'card',
    name: 'Restaurants diagram',
    question: '',
    answers: '',
    icon: '',
    background: 'card-restaurants',
    p: "Keto diet doesn't require that you prepare all your meals by yourself. There are plenty of options you can find at the local restaurant, or even the supermarket.",
    help: "Keto diet doesn't require that you prepare all your meals by yourself. There are plenty of options you can find at the local restaurant, or even the supermarket.",
  },
  {
    page: 23,
    type: 'quiz',
    name: 'Skills',
    question: 'What is the level of your cooking skills?',
    answers: [
      'I CAN’T COOK',
      'I HAVE BEGINNER SKILLS',
      'MY SKILLS ARE MODERATE',
      'I AM AN EXPERT IN THE KITCHEN',
    ],
    icon: 'icon-cooking-skills',
    background: 'bg-18',
    p: '',
    help: "Even if you start Keto with beginner cooking skills, following your personalized meal plan will help you start enjoying the process of preparing your food.",
  },
  {
    page: 24,
    type: 'choice-line',
    name: 'Drink',
    question: 'What do you drink during the day?',
    answers: [
      { name: 'drink', value: 'COFFE', type: 'answer' }, ///имя у всех чекбоксов должно быть одинаково
      { name: 'drink', value: 'TEA', type: 'answer' },
      { name: 'drink', value: 'WATER', type: 'answer' },
      { name: 'drink', value: 'SODA', type: 'answer' },
      { name: 'drink', value: 'JUICE', type: 'answer' },
      { name: 'drink', value: 'SOFT DRINK', type: 'answer' },
      { name: 'drink', value: 'None of the above', type: 'none' }, ///отрицательный тип ответа должен стоять всегда вконце и type: 'none'
    ],
    icon: 'icon-drink-during-day',
    background: 'bg-19',
    p: 'You can choose multiple options:',
    help: "Some drinks may increase your carb intake, so it is better to follow the instructions of your meal plan, where you will find what is best to drink during Keto.",
  },
  {
    page: 25,
    type: 'quiz',
    name: 'Water',
    question: 'How much water do you drink per day?',
    answers: [
      'LESS THAN 2 GLASSES',
      '2-4 GLASSES',
      '4-6 GLASSES',
      '6-8 GLASSES',
      'MORE THAN 8 GLASSES',
    ],
    icon: 'icon-water-per-day',
    background: 'bg-20',
    p: '',
    help: "The Keto diet has a diuretic effect which increases the hydration needs of the organism. Drinking enough water will help you make the process of changing your body fuel quicker.",
  },
  {
    page: 26,
    type: 'card',
    name: 'Water diagram',
    question: '',
    answers: '',
    icon: '',
    background: 'card-water',
    p: 'Most people got even better results combining Keto with higher water intake. At the end of the quiz we will recommend you a personal daily water intake during your Keto transformation.',
    help: "Most people got even better results combining Keto with higher water intake. At the end of the quiz we will recommend you a personal daily water intake during your Keto transformation.",
  },
  {
    page: 27,
    type: 'quiz',
    name: 'Alcohol',
    question: 'Do you consume alcohol?',
    answers: ['YES', 'NO', 'OCCASIONALLY'],
    icon: 'icon-consume-alcohol',
    background: 'bg-21',
    p: '',
    help: "There are some alcohols which are low-carb and Keto-friendly like wine, vodka, whiskey, gin, tequila, rum and others. Of course, you can consume them in limited quantity as they are high in calories which can impact the weight loss process.",
  },
  {
    page: 28,
    type: 'choice-line',
    name: 'Motivation',
    question: 'What motivates you the most?',
    answers: [
      { name: 'motivation', value: 'MY FAMILY', type: 'answer' }, ///имя у всех чекбоксов должно быть одинаково
      { name: 'motivation', value: 'MY FRIENDS', type: 'answer' },
      { name: 'motivation', value: 'MY COLLEAGUES', type: 'answer' },
      { name: 'motivation', value: 'GOOD EXAMPLE FROM SUCCESSFUL PEOPLE', type: 'answer' },
      { name: 'motivation', value: 'I’VE ALWAYS BEEN SELF-MOTIVATED', type: 'answer' },
      { name: 'motivation', value: 'I LACK MOTIVATION', type: 'answer' },
      { name: 'motivation', value: 'None of the above', type: 'none' }, ///отрицательный тип ответа должен стоять всегда вконце и type: 'none'
    ],
    icon: 'icon-motivates-you-most',
    background: 'bg-22',
    p: 'You can choose multiple options:',
    help: "The main factor behind your healthy weight-loss transformation is your motivation. Every journey starts with the right mindset, so find what drives you forward, and we will help with the rest.",
  },
  {
    page: 29,
    type: 'quiz',
    name: 'Journey',
    question: 'When do you want to start your keto journey?',
    answers: ['RIGHT NOW', 'NEXT WEEK', 'NEXT MONTH', 'AFTER A FEW MONTHS'],
    icon: 'icon-start-keto-journey',
    background: 'bg-23',
    p: '',
    help: "The earlier you start, the sooner you will reach your goals.",
  },
  {
    page: 30,
    type: 'card',
    name: 'Water diagram',
    question: '',
    answers: '',
    icon: '',
    background: 'card-your-way',
    p: "Actually, Your Keto journey has already started with a small step towards your target. Filling this quiz made you think about your lifestyle, and brain activity is one of the things that make our body uses a lot of energy.Now let's keep up with the progress and use that first step as a building block to your success. Continue to the next step to learn about important metrics, such as BMI, Metabolic age, Daily water intake and more useful info.",
    help: "Now let's keep up with the progress and use that first step as a building block to your success. Continue to the next step to learn about important metrics, such as BMI, Metabolic age, Daily water intake and more useful info.",
  },
  {
    page: 31,
    type: 'choice-line',
    name: 'Body parts',
    question: 'Which body area do you need to focus on during your weight loss process?',
    answers: [
      { name: 'body-parts', value: 'ARMS', type: 'answer' }, ///имя у всех чекбоксов должно быть одинаково
      { name: 'body-parts', value: 'LOVE HANDLES', type: 'answer' },
      { name: 'body-parts', value: 'CHEST', type: 'answer' },
      { name: 'body-parts', value: 'BELLY', type: 'answer' },
      { name: 'body-parts', value: 'THIGHS AND HIPS', type: 'answer' },
      { name: 'body-parts', value: 'None of the above', type: 'none' }, ///отрицательный тип ответа должен стоять всегда вконце и type: 'none'
    ],
    icon: 'icon-body-parts',
    background: 'bg-24',
    p: 'You can choose multiple options:',
    help: "Ketogenic diet tend to reduce total weight and body fat percentage much more effective than low-fat diets.",
  },
  {
    page: 32,
    type: 'measurements',
    name: 'Measurements',
    question: '',
    answers: '',
    icon: '',
    background: '',
    p: '', //последняя страница для снятия замеров
    help: "This meal program is individual and takes your body measurements into consideration.",
  },
];

export const qtyPages = pages.length;
